name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'
    branches:
      - main  # Ensures tag must be on the main branch

jobs:
  build-and-publish:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest

    if: github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v') && github.ref_name != '' && github.ref_protected == true && github.repository == 'Jordonh18/sanitizr' && github.event.base_ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install build tools
        run: python -m pip install --upgrade build twine

      - name: Build the package
        run: python -m build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: python -m twine upload dist/*
